#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🟡 Running code formatting and checks..."

npx lint-staged
if [ $? -ne 0 ]; then
  echo "🔴 Commit blocked: Fix errors before committing"
  exit 1
fi

npx tsc --noEmit --skipLibCheck
if [ $? -ne 0 ]; then
  echo "🔴 Commit blocked: TypeScript errors detected"
  exit 1
fi

echo "🟢 All checks passed. Proceeding with commit"
